# Header
navbar_brand: /images/logo.png
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- about
- archive
- tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon:
twitter_id: 'shaneschurch'
google_plus:
fb_admins:
fb_app_id:
